server:
  port: 8080
  servlet:
    context-path: /bookkeeping-server

spring:
  application:
    name: bookkeeping-server
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.bookkeeping: debug
